# Generated by Django 4.2.7 on 2023-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights', '0002_ingredient_unit_alter_ingredient_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
